version: '3'
services:
  ping-service:
    container_name: ping-service
    build: ./ping-service
    image: ilnurnasybullin/ping-service:0.0.1
    ports:
      - "9000:9000"
  pong-service:
    container_name: pong-service
    build: ./pong-service
    image: ilnurnasybullin/pong-service:0.0.1
    ports:
      - "9005:9005"